#!/bin/bash

mkdir home

PATHIN="$(pwd)/home"

#Files to remove other ongoing sessions of the analuysis, comment if you want to have more open sessions at the same time
docker stop pijuan_torregrosa
docker rm pijuan_torregrosa

#Channel of the localhost browser where to show the jupyterlab session
CHANNEL=10000

docker run --rm \
           -p $CHANNEL:8888 \
           --name pijuan_torregrosa \
           --mount type=bind,source=$PATHIN,destination=/home/jovyan \
           -e JUPYTER_ENABLE_LAB=yes \
           pijuan_torregrosa 
           
docker stop pijuan_torregrosa
docker rm pijuan_torregrosa
