#GLOBAL PARAMETERS
## HVGs
HVG_METHOD = "seurat"
N_HVG = None
##PCs
USE_HVGs = True
N_PCS = 50
##Neighbours
METRIC = "correlation"
N_NEIGBOURS = 25

#SAMPLE PARAMETERS
##HVGs
RECOMPUTE_HVGS = False
##PCs
RECOMPUTE_PCS = True
##Doublets
MAX_N_COUNTS = 39000
DOUBLET_SCORE_MAX_THRESHOLD = 0.15
DOUBLET_LOUVAIN_RESOLUTION = 1  
##Stripped
MIN_MT_FRACTION = 0.0022
##Cluster threshold
CLUSTER_THRESHOLD = 0.25
##Remove outliers
DISCONNECTION_DISTANCE = 7
MIN_CLUSTER_SIZE = 15

#SAVING PARAMETERS
SAVING_VERSION = ""